#!/usr/bin/env zsh

source util

dry="0"
while [[ $# -gt 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

cd $target/dotfiles
log "Copying Scripts"
if [[ "$(uname -s)" == "Darwin" ]]; then
    scripts="$(find ./scripts -maxdepth 1 -mindepth 1 -perm +111 -type f)"
else
    scripts="$(find ./scripts -maxdepth 1 -mindepth 1 -executable -type f)"
fi
for script in $scripts; do
    log $script
    copy_file "$script" "$target/bin"
done

configs="$(find ./.config -mindepth 1 -maxdepth 1 -type d)"
for config in $configs; do
    log $config
    copy_dir $config "$HOME/.config"
done

log "Copying Configs"
copy_dir .emacs.d $HOME
copy_file ".config/.profile" $HOME
copy_file ".config/shells/zsh/.zshrc" $HOME

log "Copying Self to ~/personal/bin"
copy_file dev-env $target/bin
copy_file util $target/bin

log "Setting Up Symlinks"
execute ln -sf $HOME/.profile $HOME/.zprofile

