#!/bin/zsh

source $HOME/personal/dotfiles/util

version="v0.10.2"

git clone -b $version https://github.com/neovim/neovim.git $target/neovim
sudo apt install ninja-build gettext cmake unzip curl build-essential
cd $target/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
make CMAKE_INSTALL_PREFIX=$target install

