#!/bin/sh

DISTRO=$(grep '^NAME=.*$' /etc/os-release | sed 's/NAME=//g')

fedora-install() {
    sudo dnf install @development-tools -y
    sudo dnf install @virtualization -y
    sudo dnf install gdb clangd git tmux zsh neovim golang fzf -y
}

gentoo-install() {
    PACKAGES=(dev-vcs/git               \
        app-misc/tmux                   \
        app-editors/neovim              \
        dev-lang/go                     \
        app-shells/fzf                  \
        app-shells/zsh                  \
        kde-plasma/plasma-meta          \
        kde-apps/kdecore-meta           \
        x11-themes/windowmaker-themes   \
        x11-wm/windowmaker              \
        www-client/firefox              \
        sys-fs/xfsdump                  \
        x11-terms/ghostty               \
        x11-terms/ghostty-terminfo      \
        sys-process/htop                \
        sys-process/btop                \
        gnustep-base/gnustep-back-cairo \
        gnustep-base/gnustep-back-xlib  \
        gnustep-base/gnustep-base       \
        gnustep-base/gnustep-gui        \
        gnustep-base/gnustep-updater    \
        mail-client/thunderbird)

    for PACKAGE in ${PACKAGES[*]};
    do
        sudo emerge --ask $PACKAGE
    done
}

unknown() {
    printf "Error: Unknown Distro '%s'.\n" $DISTRO > /dev/stderr
    exit 1
}

FUNCTION="unknown"

case $DISTRO in
    Fedora)
        FUNCTION="fedora-install"
        ;;
    Gentoo)
        FUNCTION="gentoo-install"
        ;;
    *)
        FUNCTION="unknown"
        ;;
esac

$FUNCTION

