set-option -sa terminal-overrides ",xterm*:Tc"
set -s escape-time 0
set -g mouse on

set-option -g history-limit 100000

bind r source-file ~/.tmux.conf
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind t split-window -h -c "#{pane_current_path}" "ff"
bind-key -r f run-shell "tmux neww ~/personal/bin/tmux-sessionizer"
bind-key -r T run-shell "~/personal/bin/tmux-sessionizer ~/Projects"

