#!/bin/sh

# OpenBSD does not have the -G flag
if [[ "$(uname -s)" == "OpenBSD" ]]
then
	alias \
		la="ls -Ah" \
		ls="ls -h" \
		l="ls -lAh"
else
	alias \
		la="ls -AhG" \
		ls="ls -Gh" \
		l="ls -lAhG"
fi

alias \
	cp="cp -v" \
	rm="rm -v" \
	mv="mv -v" \
 	vim="nvim" \
	..="cd .." \
	...="cd ../.." \
	.3="cd ../../.." \
	.4="cd ../../../../" \
	.5="cd ../../../../.." \
	zshup="source $HOME/.config/shells/zsh/.zshrc" \
	gc="git clone" \
	gu="git add -u" \
	m="micro" \
	v="nvim" \
	python="python3.10" \
	pip="pip3.10"

