#!/bin/sh
alias \
 	la="ls -A --color" \
	ls="ls -h --color" \
	l="ls -lhA --color" \
	calc="calc && rm ~/.calc_history" \
	gnuplot="gnuplot && rm ~/.gnuplot_history" \
	tty-clock="tty-clock -tcC 4" \
	cp="cp -v" \
	rm="rm -v" \
	mv="mv -v" \
	nvidia-settings='nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings' \
	minecraft-launcher="minecraft-launcher ; rm -r ~/GPUCache" \
	twin='twin ; rm $HOME/.TwinAuth' \
	sd="sudo shutdown -h now" \
 	vim="nvim" \
	v="nvim" \
	f="vifm" \
	..="cd .." \
	...="cd ../.." \
	.3="cd ../../.." \
	.4="cd ../../../../" \
	.5="cd ../../../../.." \
	pacsyu="sudo pacman -Syyu" \
	zshup="source $HOME/.config/shells/zsh/.zshrc" \
	b="cd ~/.local/bin" \
	d="cd ~/Documents" \
	bk="cd ~/Documents/books" \
	dw="cd ~/Downloads" \
	g="cd ~/Documents/projects/gitlab" \
	c="cd ~/.config"
