set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after
set number relativenumber
set wildmode=longest,list,full
map <leader>o :setlocal spell! spelllang=en_us<CR>
autocmd BufWritePre * %s/\s\+$//e
syntax on
