#!/usr/bin/env bash

if [[ -z "$(stat "$(namespace)/font")" ]];
then
    fontsrv &
fi

case "$(uname -s)" in
    Darwin)
        FONT="/mnt/font/JetBrainsMonoNL-Regular/14a/font"
        ;;
    *)
        FONT="/mnt/font/JetBrainsMono-Regular/12a/font"
        ;;
esac

"$PLAN9/bin/acme" -f "$FONT"

