#!/bin/sh

char=$(cut -d ';' -f1 ~/.local/share/unicode | dmenu -i -l 30 | sed "s/ .*//")

[ -z "$char" ] && exit

if [ -n "$1" ]; then
	xdotool type "$char"
else
	echo "$char" | tr -d '\n' | xclip -selection clipboard
	notify-send "'$char' copied to clipboard." &
fi
