## Arrow Key Functions
set -o vi

export SHELLDIR="$XDG_CONFIG_HOME/shells"

for CONFIG_FILE in $SHELLDIR/utils/*;
do
    [[ -f $CONFIG_FILE ]] && . $CONFIG_FILE
done

OS="$(uname -s)"
for CONFIG_FILE in $SHELLDIR/utils/$OS/*;
do
    [[ -f $CONFIG_FILE ]] && . $CONFIG_FILE
done

HISTFILE="$XDG_CACHE_HOME/kshHIST"
HISTSIZE=5000
PS1=$(printf "[${GREEN}%s${NORM}] " '$(_collapsed_pwd)')
